// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using recipe_helper;

namespace recipe_helper.Migrations
{
    [DbContext(typeof(RecipeContext))]
    [Migration("20211004193039_initialMigration")]
    partial class initialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("recipe_helper.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<string>("Food")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 2,
                            Food = "tbs curry powder",
                            RecipeId = 1
                        },
                        new
                        {
                            Id = 2,
                            Amount = 5,
                            Food = "cups of rice",
                            RecipeId = 1
                        },
                        new
                        {
                            Id = 3,
                            Amount = 2,
                            Food = "pounds of chicken",
                            RecipeId = 1
                        },
                        new
                        {
                            Id = 4,
                            Amount = 1,
                            Food = "tsp of salt",
                            RecipeId = 1
                        },
                        new
                        {
                            Id = 5,
                            Amount = 1,
                            Food = "vanilla bean",
                            RecipeId = 2
                        },
                        new
                        {
                            Id = 6,
                            Amount = 3,
                            Food = "soy beans",
                            RecipeId = 2
                        },
                        new
                        {
                            Id = 7,
                            Amount = 68,
                            Food = "coffee beans",
                            RecipeId = 2
                        },
                        new
                        {
                            Id = 8,
                            Amount = 1,
                            Food = "cup of water",
                            RecipeId = 2
                        },
                        new
                        {
                            Id = 9,
                            Amount = 1,
                            Food = "frozen pizza",
                            RecipeId = 3
                        });
                });

            modelBuilder.Entity("recipe_helper.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Summary")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Recipes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Curry",
                            Summary = "A yellow curry"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Vanilla Soy Milk Latte",
                            Summary = "A three bean soup"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Pizza",
                            Summary = "Popular Italish-American"
                        });
                });

            modelBuilder.Entity("recipe_helper.Ingredient", b =>
                {
                    b.HasOne("recipe_helper.Recipe", null)
                        .WithMany("Ingredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
